// create web server with express
// npm install express
// npm install body-parser
// npm install mysql
// npm install express-session
// npm install multer
// npm install fs
// npm install ejs
// npm install express-ejs-layouts
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-kakao
// npm install passport-naver
// npm install connect-flash
// npm install bcrypt-nodejs
// npm install cookie-parser
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install socket.io
// npm install multer
// npm install fs
// npm install ejs
// npm install express-ejs-layouts
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-kakao
// npm install passport-naver
// npm install connect-flash
// npm install bcrypt-nodejs
// npm install cookie-parser
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install socket.io
// npm install multer
// npm install fs
// npm install ejs
// npm install express-ejs-layouts
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-kakao
// npm install passport-naver
// npm install connect-flash
// npm install bcrypt-nodejs
// npm install cookie-parser
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install socket.io
// npm install multer
// npm install fs
// npm install ejs
// npm install express-ejs-layouts
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-kakao
// npm install passport-naver
// npm install connect-flash
// npm install bcrypt-nodejs
// npm install cookie-parser
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install socket.io
// npm install multer
// npm install fs
// npm install ejs
// npm install express-ejs-layouts
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-kakao
// npm install passport-nav


